title: hcct-jekyll
email: kens7601@hotmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""


# Build settings
theme: minima
plugins:
  - jekyll-feed

